---
#
- name: craete groovy ref directory
  file:
    path: "{{ jenkins_reference_directory }}/init.groovy.d"
    state: directory

- name: init groovy script
  template:
    src: init.groovy.j2
    dest: "{{ jenkins_reference_directory }}/init.groovy.d/tcp-slave-agent-port.groovy"

- name: configure jenkins command
  template:
    src: jenkins-command.j2
    dest: /usr/local/bin/jenkins
    owner: "{{ jenkins_user }}"
    group: "{{ jenkins_group }}"
    mode: "u+x"

- name: configure jenkins service
  template:
    src: jenkins-service.j2
    dest: /etc/systemd/system/jenkins.service
  become: yes

- name: enable service
  command: systemctl daemon-reload
  become: yes
  ignore_errors: yes

- name: enable service
  command: systemctl enable jenkins.service
  become: yes
  ignore_errors: yes
